<?php

/**
 * Implementation of hook_ENTITY_TYPE_presave
 */
function calculatefield_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $daterangearray = $entity->get('field_datereange')->getValue();
  $daterangestartvalue = strtotime($daterangearray[0]['value']);
  $daterangeendvalue = strtotime($daterangearray[0]['end_value']);
  $value = $daterangeendvalue - $daterangestartvalue;
  $entity->set('field_durasi', $value . ' detik');
}
